### ISSUE TITLE
permission denied issue in dev-net

### ISSUE THREAD

**Issue by pgwadapool** [input-output-hk/mithril#459] opened 2022-08-27 04:27 UTC
## Context & versions
I am running dev-net as per the documentation using remote docker

## Actual behavior
mithril-signer-node-pool1_1  | Error: InitializationError(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })
mithril-signer-node-pool1_1  | {"msg":"Started","v":0,"name":"slog-rs","level":20,"time":"2022-08-27T04:24:38.210862051Z","hostname":"52c3ad6c4a16","pid":1,"config":"Config { cardano_cli_path: \"/app/bin/cardano-cli\", cardano_node_socket_path: \"/data/ipc/node.sock\", network_magic: Some(42), network: \"devnet\", aggregator_endpoint: \"http://mithril-aggregator:8080/aggregator\", party_id: \"pool1zpc8krqqdd7ahy20uqzqqj7hmskdelr3aplpncq8v3n9skmyq06\", run_interval: 700, db_directory: \"/data/db\", data_stores_directory: \"/data/mithril/signer-node-pool1/stores\" }","run_mode":"dev"}
mithril-signer-node-pool1_1  | Error: InitializationError(Os **{ code: 13, kind: PermissionDenied, message: "Permission denied" })**

I am not sure what the issue is

**Comment by jpraynaud** [comment] 2022-08-29 13:55
Hi @pgwadapool, thanks for your feedback :slightly_smiling_face: 

Could send us the following information so that we can identify the issue?
* Steps to reproduce
* System info
* Full logs of all docker nodes

**Comment by pgwadapool** [comment] 2022-08-29 14:21
I am following the steps outlined in the documentation
MITHRIL_IMAGE_ID=latest NUM_BFT_NODES=1 NUM_POOL_NODES=2 ./devnet-run.sh

I am running on Ubuntu 22.04 x86

Attached logs 
[node-bft.log](https://github.com/input-output-hk/mithril/files/9445311/node-bft.log)
[node1.log](https://github.com/input-output-hk/mithril/files/9445312/node1.log)
[node2.log](https://github.com/input-output-hk/mithril/files/9445313/node2.log)
[devnet-20220827130749.log](https://github.com/input-output-hk/mithril/files/9445316/devnet-20220827130749.log)
[devnet-20220827130749.log](https://github.com/input-output-hk/mithril/files/9445317/devnet-20220827130749.log)

**Comment by jpraynaud** [comment] 2022-08-31 09:48
It looks like there are some permissions issues with your remote docker setup. 
Unfortunately, we have not been able to reproduce the problem on our end. 
Can you provide us with more information on the actual remote docker setup you are using?

In the mean time, we have added an option on the volumes of the `docker-compose.yaml` file that may fix the problem in #467 
Can you check if this fix is resolving the problem?

**Comment by pgwadapool** [comment] 2022-08-31 13:49
This did not solve the problem.
Let me dig into docker

**Comment by pgwadapool** [comment] 2022-09-09 04:21
This was an issue in docker installation and this is now resolved at my end.
I am able to successfully run devnet
Closing the issue

**Comment by jpraynaud** [comment] 2022-09-09 07:32
Hi @pgwadapool thanks for your feedback , I close the issue :+1:

**Closed by jpraynaud** 2022-09-09 07:32 UTC
Labels: bug, D-medium, P-medium
